### PR TITLE
Typo and add HTML & CSS resources 

### PR DESCRIPTION
**Pull request by raakesh**
Typo correction in [link](https://github.com/coderplex/learn/blob/master/web-dev/Backend/laravel/2-curriculum/4-final-project.md)
Added HTML & CSS resources to [link](https://github.com/coderplex/learn/blob/master/web-dev/Frontend/learn-basics.md)

### CODE REVIEW

**Comment by duttakapil** [comment]
Hey, thanks for the PR! Typo correction looks good, but for the resources, I don't think there is any need to provide Shayhowe's HTML and CSS guide, since we're already linking to the freeCodeCamp curriculum and that covers most of the material covered by Shay. We do not want to keep adding more and more resources, because there are quite a lot on the Internet, we want to pick one or two best ones and recommend that. 

Also, the Web Fundamentals learning guide will require a complete new version. It would need to look something similar to the Laravel guide.

**Comment by duttakapil** [comment]
Magic of CSS looks like a good resource. Never came across it before. Could you link to [the website version](http://adamschwartz.co/magic-of-css/), instead of the GitHub repo?

**Comment by raakesh** [comment]
@duttakapil Removed Shay howe resource from the list and added website version of Magic of CSS.

**Comment by raakesh** [comment]
@duttakapil  I've removed Shayhowe's HTML and CSS guide and added website link to Magic of CSS rather than github repo.

**Comment by duttakapil** [comment]
Thanks for your contribution @raakesh :D

**Pull request merged**
