### PR TITLE
Add more tasks and resources to ReactJS guide

### PR DESCRIPTION
**Pull request by elevenpassin**
Added a couple of tasks to the ReactJS Guide

### CODE REVIEW

**Comment by duttakapil** [comment]
I will let @M-ZubairAhmed and @aravindballa respond to this

**Comment by elevenpassin** [comment]
@aravindballa There are React bindings which allow you to use Flow types, Typescript, ReasonML for building React applications as well.

**Comment by duttakapil** [comment]
What should we do with this PR @aravindballa @M-ZubairAhmed

**Comment by aravindballa** [comment]
I am good with this. Let @M-ZubairAhmed review it once and we can merge. 🍦

**Pull request merged**
