### PR TITLE
added hooks documentation

### PR DESCRIPTION
**Pull request by vamshi9666**

### CODE REVIEW

**Comment by duttakapil** [comment]
@aravindballa @M-ZubairAhmed can you guys review this

**Comment by aravindballa** [comment]
Shall we include `useEffect` hook as well? (After `useState`)

Because that is mostly used to build custom hooks.

**Comment by vamshi9666** [comment]
@aravindballa in which table `useEffect ` should be included. Predefined hooks or custom Hooks ?

**Comment by aravindballa** [comment]
> @aravindballa in which table `useEffect ` should be included. Predefined hooks or custom Hooks ?

Predefined

**Comment by vamshi9666** [comment]
how about context Hook ? should that be added too

**Comment by vamshi9666** [comment]
these are the list of hooks inbuilt 

- [ ] useState

- [ ] useEffect

- [ ] useContext

- [ ] useReducer

- [ ] useCallback

- [ ] useMemo

- [ ] useRef

- [ ] useImperativeHandle

- [ ] useLayoutEffect

- [ ] useDebugValue

**Comment by vamshi9666** [comment]
if they're too many , we can sum them up and all be included in one table

**Comment by aravindballa** [comment]
Maybe we can add this page which contains all of them - https://reactjs.org/docs/hooks-reference.html and have only the important ones in the table.

**Comment by vamshi9666** [comment]
@aravindballa check the important hooks in the list above. so that ones will be in table.

**Comment by aravindballa** [comment]
Lets include these three in predefined
- useState
- useEffect
- useContext

And add a link so that they can look at all the hooks if they want

**Comment by vamshi9666** [comment]
closing because of outdates and inactive discussions

**Pull request closed without merging**
